#106   add option to show user favorite cities
blumilksoftware/escooters pull request #115
Opened 2023-08-09 08:49 UTC by BarTracz

2023-08-29 09:25 UTC, krzysztofrewak requested changes

2023-08-29 09:25 UTC, krzysztofrewak commented on app/Http/Controllers/FavoritesController.php
> +        return Favorites::where("user_id", $userId)
```suggestion
        return Favorites::query()->where("user_id", $userId)
```

2023-08-29 09:25 UTC, krzysztofrewak commented on app/Http/Controllers/FavoritesController.php
> +    public function show(Request $request): array
I would prefer to return JsonResponse in controllers. I know that arrays are automatically converted into response objects, but I like to have everything on its right place.

2023-09-01 01:22 UTC, vojcc commented
I think we can make something like /my-cities page which would look like thiat:

![image](https://github.com/blumilksoftware/escooters/assets/92044526/1232e11c-13e8-4d93-817c-c69c8003f5ca)

Simple list with map.

2023-09-04 07:46 UTC, EwelinaSkrzypacz commented
I'm closing this, because #137 has already solved the issue.

2023-09-04 07:46 UTC, closed without merging